import { ServiceItem, WorkComparisonItem, ReviewItem, FaqItem } from '../types';

export const COMPANY_INFO = {
  name: "ProBrush Premium Painting",
  tagline: "Premium Quality that you can Trust!",
  phone: "(555) 792-7874",
  phoneRaw: "5557927874",
  email: "estimates@probrushpremiumpainting.com",
  serviceArea: "Greater Metro Area, North Suburbs, East Hills & Surrounding Communities",
  hours: {
    weekdays: "Monday – Friday: 7:00 AM – 6:00 PM",
    saturday: "Saturday: 8:00 AM – 4:00 PM",
    sunday: "Sunday: Closed (Emergency & Commercial by appointment)",
  },
  credentials: [
    "Fully Licensed & Bonded",
    "$2,000,000 General Liability Insurance",
    "Workers' Compensation Covered",
    "EPA Lead-Safe Certified",
  ],
  stats: [
    { label: "Free Written Estimates", value: "100%" },
    { label: "Clean Work Guarantee", value: "Every Job" },
    { label: "Premium Grade Paints", value: "Sherwin-Williams & Benjamin Moore" },
    { label: "Customer Satisfaction", value: "Quality Focused" },
  ],
};

export const SERVICES_LIST: ServiceItem[] = [
  {
    id: "interior-painting",
    number: 1,
    title: "Interior Painting",
    tagline: "Flawless walls, ceilings, doors, and trim with zero mess left behind.",
    description: "Professional interior painting for homes, offices and commercial spaces.",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1000&q=80",
    iconName: "Paintbrush",
    features: [
      "Walls, ceilings, crown molding & baseboards",
      "Full furniture & flooring masking protection",
      "Drywall patching & hairline crack repair",
      "Zero-VOC & low-odor eco-friendly paint options",
    ],
    processSteps: [
      "Room clearance & complete drop cloth floor shielding",
      "Surface sanding, minor spackling & caulk sealing",
      "Even primer coat application where required",
      "Two uniform finish coats for lasting color depth",
      "Detailed cleanup, vacuuming & client walkthrough",
    ],
    idealFor: "Living rooms, kitchens, bedrooms, corridors, corporate boardrooms, executive suites.",
  },
  {
    id: "exterior-painting",
    number: 2,
    title: "Exterior Painting",
    tagline: "Weather-resistant coatings engineered to endure heat, rain, and cold.",
    description: "Durable exterior painting designed to improve appearance and protect surfaces.",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80",
    iconName: "Home",
    features: [
      "Siding, brick, stucco, wood, fascia & soffits",
      "Heavy-duty weatherproofing & elastomeric sealants",
      "Mildew-resistant & UV-reflective premium paints",
      "Gutter line and architectural trim precision",
    ],
    processSteps: [
      "Deep pressure wash to strip chalking and grime",
      "Scraping loose paint & feather sanding edges",
      "Exterior primer application on bare wood or masonry",
      "Precision spray & back-brushing for complete penetration",
      "Spotless perimeter tidy-up and final inspection",
    ],
    idealFor: "Single-family residences, townhouses, estates, storefront exteriors, multi-family units.",
  },
  {
    id: "surface-cleaning",
    number: 3,
    title: "Surface Cleaning",
    tagline: "High-grade pressure washing and deep decontamination for spotless curb appeal.",
    description: "Professional surface cleaning to remove dirt, buildup and unwanted marks before or after painting.",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1000&q=80",
    iconName: "Sparkles",
    features: [
      "Driveways, sidewalks, stone patios & walkways",
      "Siding soft-wash preventing structural water damage",
      "Deck & fence pre-stain mold & algae eradication",
      "Efflorescence & environmental grime removal",
    ],
    processSteps: [
      "Plant & sensitive landscape pre-wetting & cover",
      "Eco-safe detergent application to dissolve grime",
      "Calibrated PSI pressure rinse matching surface density",
      "Post-wash inspection ensuring no streaking or gouging",
    ],
    idealFor: "Concrete pads, pavers, vinyl siding, composite decks, commercial entryways.",
  },
  {
    id: "residential-painting",
    number: 4,
    title: "Residential Painting",
    tagline: "Transforming family homes into modern, vibrant, high-value living spaces.",
    description: "High-quality painting solutions for homeowners.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80",
    iconName: "Users",
    features: [
      "Comprehensive whole-home interior & exterior packages",
      "Kitchen cabinet spraying & refinishing",
      "Accent walls, color consultations & sampling",
      "Respectful, tidy crew who treat your home with care",
    ],
    processSteps: [
      "In-person lighting and color verification",
      "Daily staging schedules minimizing disruption",
      "High-adhesion primers and durable washable enamels",
      "End-of-day tidy guarantee so you can live comfortably",
    ],
    idealFor: "Home renovations, move-in/move-out repaints, seasonal updates, curb appeal boosts.",
  },
  {
    id: "commercial-painting",
    number: 5,
    title: "Commercial Painting",
    tagline: "On-time, within-budget commercial coating with minimal operational downtime.",
    description: "Professional painting services for offices, commercial properties and businesses.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80",
    iconName: "Building2",
    features: [
      "Flexible night & weekend scheduling for zero disruption",
      "High-durability scuff-resistant commercial coatings",
      "Retail spaces, corporate offices, medical clinics & HOA",
      "Full insurance compliance and COI certificates",
    ],
    processSteps: [
      "Comprehensive scope-of-work documentation",
      "Phased workspace scheduling by department",
      "Industrial spray & roller rapid application",
      "Sign-off protocol with facility managers",
    ],
    idealFor: "Office buildings, clinics, retail storefronts, warehouses, hospitality centers.",
  },
  {
    id: "surface-preparation",
    number: 6,
    title: "Surface Preparation",
    tagline: "The foundation of enduring beauty: 80% of paint longevity is in the prep.",
    description: "Proper preparation, cleaning, patching and priming for a smooth, long-lasting finish.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1000&q=80",
    iconName: "ShieldCheck",
    features: [
      "Dustless sanding & deep substrate cleaning",
      "Caulking joints, baseboards, and window perimeters",
      "Stain-blocking primer on water marks & smoke damage",
      "Rotted wood repair & synthetic wood filler patching",
    ],
    processSteps: [
      "Raking light inspection to identify surface flaws",
      "Compound application and feathered feather-sanding",
      "Complete vacuuming and tack-cloth wipedown",
      "Bonding primer seal for maximum topcoat adhesion",
    ],
    idealFor: "Older plaster walls, weather-beaten wood siding, textured ceilings, high-traffic doors.",
  },
];

export const WHY_CHOOSE_US_ITEMS = [
  {
    id: "quality",
    title: "Premium Quality",
    description: "We use exclusively premium grade paints and stains (Sherwin-Williams, Benjamin Moore) formulated for rich pigment depth and maximum scrubbability.",
    icon: "Award",
  },
  {
    id: "workmanship",
    title: "Professional Workmanship",
    description: "Our painters are skilled craftspeople trained in uniform cut-ins, ultra-smooth spray finishes, and strict quality control standards.",
    icon: "Brush",
  },
  {
    id: "reliable",
    title: "Reliable Service",
    description: "We show up promptly at the scheduled hour, communicate transparently throughout the project, and meet all agreed-upon deadlines.",
    icon: "Clock",
  },
  {
    id: "detail",
    title: "Attention to Detail",
    description: "Crisp straight cut lines, seamlessly caulked seams, masked hardware, and thorough surface preparation before a single drop of paint touches the wall.",
    icon: "CheckCircle2",
  },
  {
    id: "clean",
    title: "Clean & Professional Finish",
    description: "Floors, furniture, and landscaping are meticulously masked. At the end of every day, our worksite is left organized, vacuumed, and spotless.",
    icon: "Sparkle",
  },
  {
    id: "satisfaction",
    title: "Customer Satisfaction",
    description: "We conduct a thorough final walkthrough alongside you. The final balance is only due when you are completely satisfied with the results.",
    icon: "ThumbsUp",
  },
];

export const WORK_COMPARISONS: WorkComparisonItem[] = [
  {
    id: "interior-living-room",
    title: "Contemporary Interior Living Room",
    category: "Interior",
    description: "Transformed a dated, scuffed living space into a bright, airy architectural sanctuary with custom warm neutral tones and crisp white baseboards.",
    beforeImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    afterImage: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
    beforeLabel: "Before (Worn Walls & Uneven Coat)",
    afterLabel: "After (ProBrush Satin Finish)",
    details: "Full prep, drywall repair, 2 coats Benjamin Moore Regal Select",
    specs: "Residential Interior • Living Room & High Ceilings",
  },
  {
    id: "exterior-residential-home",
    title: "Modern Craftsman Exterior Resurfacing",
    category: "Exterior",
    description: "Complete weather-protection coating with deep royal blue accents, crisp pure white eaves, and weather-sealed siding.",
    beforeImage: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1200&q=80",
    afterImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    beforeLabel: "Before (Faded & Weather Damaged)",
    afterLabel: "After (Weather-Shield Finish)",
    details: "Power-wash prep, scraping, primer, Sherwin-Williams Duration Exterior",
    specs: "Full Exterior Siding, Fascia, Trim & Front Entry",
  },
  {
    id: "commercial-corporate-space",
    title: "Executive Corporate Office Suite",
    category: "Commercial",
    description: "Weekend turnaround project painting high-traffic executive corridors and conference rooms with durable scuff-resistant commercial coating.",
    beforeImage: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    afterImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    beforeLabel: "Before (Marked Commercial Drywall)",
    afterLabel: "After (Scuff-X High-Durability)",
    details: "Completed in 48 hours over the weekend with zero employee disruption",
    specs: "Commercial Office • Conference Rooms & Entry Lobby",
  },
  {
    id: "surface-cleaning-patio",
    title: "Surface Cleaning: Concrete & Stone Pavers",
    category: "Cleaning",
    description: "Deep pressure cleaning stripping decades of moss, dirt, efflorescence, and grease before applying protective seal.",
    beforeImage: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
    afterImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
    beforeLabel: "Before (Algae & Dark Buildup)",
    afterLabel: "After (Deep Power-Cleaned)",
    details: "Rotary surface scrubber, biological cleaner, calibrated PSI rinse",
    specs: "Exterior Surface Cleaning • Walkway & Patio",
  },
  {
    id: "detailed-woodwork-trim",
    title: "Detailed Architectural Trim & Millwork",
    category: "Detailed Work",
    description: "Meticulous enamel spray finish on handcrafted fireplace mantel, coffered ceiling, and custom wainscoting.",
    beforeImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    afterImage: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80",
    beforeLabel: "Before (Yellowing Wood & Gaps)",
    afterLabel: "After (Smooth Enamel Spray)",
    details: "Wood filler, fine sanding, bonding primer, 2 coats semi-gloss enamel",
    specs: "Detailed Millwork • Custom Fireplace & Trim",
  },
];

export const REVIEWS_DATA: ReviewItem[] = [
  {
    id: "rev-placeholder-1",
    author: "Verified Customer",
    role: "Residential Homeowner",
    location: "Oakridge Hills",
    rating: 5,
    date: "Recent Project",
    projectType: "Interior Painting & Trim",
    reviewText: "Add verified customer review here.",
    verified: true,
    isPlaceholder: true,
  },
  {
    id: "rev-placeholder-2",
    author: "Verified Customer",
    role: "Commercial Property Manager",
    location: "Downtown District",
    rating: 5,
    date: "Recent Project",
    projectType: "Commercial Office Painting",
    reviewText: "Add verified customer review here.",
    verified: true,
    isPlaceholder: true,
  },
  {
    id: "rev-placeholder-3",
    author: "Verified Customer",
    role: "Homeowner",
    location: "Westfield Suburb",
    rating: 5,
    date: "Recent Project",
    projectType: "Exterior Siding & Surface Cleaning",
    reviewText: "Add verified customer review here.",
    verified: true,
    isPlaceholder: true,
  },
];

export const FAQ_LIST: FaqItem[] = [
  {
    id: "faq-1",
    question: "What painting services do you offer?",
    answer: "ProBrush Premium Painting provides a comprehensive suite of painting and surface solutions: interior painting (walls, ceilings, trim, cabinetry), exterior painting (siding, stucco, brick, decks, trim), surface cleaning (pressure washing, deep power-washing, pre-paint surface decontamination), and complete surface preparation (patching, sanding, caulk sealing, and priming). We cater to both residential homeowners and commercial clients.",
    category: "Services",
  },
  {
    id: "faq-2",
    question: "Do you provide free estimates?",
    answer: "Yes, 100%! We provide free, detailed, and completely transparent written estimates. You can either fill out our online quote form (uploading photos of your project for a fast preliminary estimate) or schedule an in-person, on-site consultation where we evaluate the space, take precise measurements, and discuss color preferences.",
    category: "Estimates & Pricing",
  },
  {
    id: "faq-3",
    question: "Do you handle both residential and commercial projects?",
    answer: "Yes. Our team is equipped for both private residential residences (single-family homes, townhouses, condos) and commercial properties (offices, retail locations, clinics, HOA communities). We also offer flexible evening and weekend scheduling for commercial clients to avoid any workplace interruption.",
    category: "Services",
  },
  {
    id: "faq-4",
    question: "Do you provide surface cleaning?",
    answer: "Yes. Surface cleaning is one of our primary core offerings. We perform professional high-pressure and soft-wash surface cleaning for driveways, patios, siding, sidewalks, and decks. Whether you need cleaning as a preparatory step before painting or as a standalone service to refresh your property's exterior, our equipment delivers pristine results.",
    category: "Cleaning",
  },
  {
    id: "faq-5",
    question: "How do I prepare my property for painting?",
    answer: "Our team handles the heavy lifting, including masking floors, taping baseboards, and covering furniture with heavy-duty drop cloths. We simply ask that you remove fragile personal items, small decor, and valuables from the work areas. For exterior projects, trimming nearby shrubs or moving patio furniture a few feet away from the walls is greatly appreciated.",
    category: "Preparation",
  },
  {
    id: "faq-6",
    question: "How long does a typical painting project take?",
    answer: "A standard single-room or small interior project typically takes 1 to 2 days. A complete residential interior or exterior generally takes between 3 to 5 business days, depending on weather and the required surface prep. We provide a clear, binding timeline in your written quote so you always know what to expect.",
    category: "Timeline",
  },
  {
    id: "faq-7",
    question: "Can I send photos of my project for an estimate?",
    answer: "Absolutely! You can easily upload photos of your rooms, walls, or exterior siding directly through our 'Get a Free Quote' form. Clear photos from multiple angles allow our estimating team to assess the scope, identify surface prep requirements, and send you a rapid preliminary quote within a few hours.",
    category: "Estimates & Pricing",
  },
];

export const SERVICE_AREAS = [
  { name: "Metro Central", zip: "90001 - 90025", active: true },
  { name: "North County & Suburbs", zip: "90210 - 90290", active: true },
  { name: "West Valley & Hills", zip: "91301 - 91367", active: true },
  { name: "South Shore & Coastal", zip: "90701 - 90840", active: true },
  { name: "East District & Heights", zip: "91701 - 91804", active: true },
  { name: "Surrounding Communities", zip: "Within 35 Miles", active: true },
];
